### ISSUE TITLE
feature request: support crop in image loader

### ISSUE THREAD

**Issue by LorinRenodeyn2PO** [limitless-angular/limitless-angular#1]
Currently, the imageloader supports a `fit` property passed in via loaderParams but the value is actually ignored and replaced by `fit=max` if present.

I propose using the actual value passed in

```
// replace
.fit((loaderParams['fit'] ?? loaderParams['height']) ? 'min' : 'max');
// with
.fit(loaderParams['fit'] ?? (loaderParams['height'] ? 'min' : 'max');
```

+ adding support for passing crop parameters as well, likely along the lines of [this example](https://dev.to/webby/crop-it-like-its-hot-cropping-images-in-sanity-v3-2i1e)

```
if (Boolean(loaderParams['crop'])) {
    /* 
     * determine crop rectangle first, then 
     * */
    imageBuilder = imageBuilder.rect(left, top, croppedWidth, croppedHeight)
}
```

**Comment by osnoser1** [comment]
Hi, I just finished the the preview-kit and visual-editing docs, I'll release today, and then I'll check this 😄
